import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="hidden">
          <Link href="/" prefetch={true}>
            About
          </Link>
          <Link href="/works">Works</Link>
          <Link href="/contact">Contact</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
